### Get many (use defaults).
GET https://localhost:7226/api/invoices

### Get many (limit the number of invoices returned).
GET https://localhost:7226/api/invoices?limit=3

### Get many (fetch the next page of records using a token).
GET https://localhost:7226/api/invoices?limit=3
                                       &token=W3siY29tcG9zaXRlVG9rZW4iOnsidG9rZW4iOiIrUklEOn5jVmdHQVBUMUpFNEZBQUFBQUFBQUFBPT0jUlQ6MSNUUkM6MyNSVEQ6ZVhUSEwreW45UldnbFhOb0NOUGFCTUo1SzFuSE1iWT0jSVNWOjIjSUVPOjY1NTY3I1FDRjo4IiwicmFuZ2UiOnsibWluIjoiIiwibWF4IjoiRkYifX0sIm9yZGVyQnlJdGVtcyI6W3siaXRlbSI6MTY3MjE5MTYxOTQzNn1dLCJyaWQiOiJjVmdHQVBUMUpFNEZBQUFBQUFBQUFBPT0iLCJza2lwQ291bnQiOjAsImZpbHRlciI6InRydWUifV0=

### Get one.
GET https://localhost:7226/api/invoices/3aeb4dbf-31ae-4eb7-b9dd-91cb62e7f593

### Create one.
POST https://localhost:7226/api/invoices
Content-Type: application/json

{
  "whoCreated": "string",
  "status": "Draft",
  "whenDue": "2022-12-29",
  "whenIssued": "2022-12-28",
  "reference": "string",
  "lineItems": [
    {
      "description": "string",
      "quantity": 0,
      "amountNet": 0,
      "amountTax": 0,
      "annotations": [
        {
          "description": "string"
        }
      ]
    }
  ]
}

### Delete one.
DELETE https://localhost:7226/api/invoices/8269a621-ac7c-4980-bc8c-589460abf522
