# @name login
POST http://localhost:8080/realms/plouton/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=test-client&username=isaac-brown&password=password&client_secret=Bj1ueFgn7VmjDbQXOZoJOwCw5Xbqqmpq

###

@authToken = {{login.response.body.$.access_token}}

### Get many (use defaults).
GET https://localhost:7226/api/v1/invoices
Authorization: Bearer {{authToken}}

### Get many (limit the number of invoices returned).
# @name getManyWithLimit
GET https://localhost:7226/api/v1/invoices?limit=3
Authorization: Bearer {{authToken}}

###

@continuationToken = {{getManyWithLimit.response.body.$.token}}

### Get many (fetch the next page of records using a token).
GET https://localhost:7226/api/v1/invoices?limit=3
                                       &token={{continuationToken}}
Authorization: Bearer {{authToken}}

### Create one.
# @name createOne
POST https://localhost:7226/api/v1/invoices
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "whoCreated": "bob from accounts",
  "status": "Draft",
  "whenDue": "2022-12-29",
  "whenIssued": "2022-12-28",
  "reference": "My reference",
  "lineItems": [
    {
      "description": "A coat",
      "quantity": 1,
      "amountNet": 10,
      "amountTax": 1.50,
      "annotations": [
        {
          "description": "What a lovely coat it is"
        }
      ]
    }
  ],
  "contact": {
    "name": "Bob Jenkins",
    "address": {
      "addressLine1": "75 Jenkins way"
    }
  }
}

###

@invoiceId = {{createOne.response.body.id}}

### Get one.
GET https://localhost:7226/api/v1/invoices/{{invoiceId}}
Authorization: Bearer {{authToken}}

### Update one.
PUT https://localhost:7226/api/v1/invoices/{{invoiceId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "status": "Draft",
  "whenDue": "2022-12-30",
  "whenIssued": "2022-12-27",
  "whenCreated": "2022-01-29T21:26:13.353+13:00",
  "reference": "Another reference",
  "lineItems": [
  ],
  "contact": {
    "name": "Bob Jenkins",
    "address": {
      "addressLine1": "75 Jenkins way"
    }
  }
}

### Delete one.
DELETE https://localhost:7226/api/v1/invoices/{{invoiceId}}
Authorization: Bearer {{authToken}}
